### ISSUE TITLE
Unable to use Raysurveyor on my dataset

### ISSUE THREAD

**Issue by Jasmeer57** [zorino/RaySurveyor-Tutorial#2]
After a successful installation of Ray surveyor, I tried it on my dataset that contains 38 contig files (FASTA format) for Acinetobacter baumannii, I tried replacing the datasets folder with my contig files in the same format as given by the example data but it is not working and showing an error. However, the example data file is working properly. After replacing the files, but an error occurred  "Rank 0 wrote survey.res/RayCommand.txt". Please let me know how can I resolve this error as I want to run Ray surveyor for KOVER and convert my sequence to KmerMatrix file for the input data. I have pasted all the photos for your reference. Hoping for a positive reply!

Thanks in advance

![working example data](https://user-images.githubusercontent.com/62324066/177961430-b5529db3-6312-4e8d-9bed-f4c02f9a5a5e.png)
![image](https://user-images.githubusercontent.com/62324066/177964968-d361c72d-8c63-4567-b115-3a226459345a.png)
![image](https://user-images.githubusercontent.com/62324066/177964098-4659299f-c236-46ca-a859-e4339bd6f3bf.png)
![image](https://user-images.githubusercontent.com/62324066/177964174-179097fd-7d9f-4e30-9215-d66e821c9237.png)

**Comment by zorino** [comment]
Hi,
might be because your file is windows encoded for end of lines,
in windows it's \r\n instead \n in linux.. if it's the case raysurveyor might only be able to read the first sequence line of each conting in the .fa files.

**Comment by Jasmeer57** [comment]
Hello sir,

Thank you for the reply sir, I had another query. 
Please let me know the directory where I should place my dataset so that Ray surveyor can access the data, I am replacing files in raysurveyor-tutorial/datasets. Is the default location the same as the one in the tutorial dataset?

**Comment by zorino** [comment]
it can access files wherever (full or relative path) they are as long as the permissions allow it.

**Comment by Jasmeer57** [comment]
It is working fine sir!

Thanks a lot for your time
